#!/bin/sh
set -e

config_file=/etc/siridb.conf

case "$1" in
    purge)
        if which ucf >/dev/null 2>&1; then
            ucf --purge $config_file
        fi
        if [ -x "`which ucfr 2>/dev/null`" ]; then
	        ucfr --purge siridb-server $config_file
        fi
        ;;
    remove)
	    ;;
esac

#DEBHELPER#
exit 0
