apiVersion: v1
kind: Service
metadata:
  labels:
    app: siridb
  name: siridb
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: status
    port: 8080
  - name: client
    port: 9000
  - name: http
    port: 9080
  - name: server
    port: 9010
  selector:
    app: siridb